# Generated by Django 5.2.5 on 2025-08-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('file', models.FileField(upload_to='data/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('key1', models.TextField()),
                ('val1', models.TextField()),
                ('key2', models.TextField()),
                ('val2', models.TextField()),
                ('key3', models.TextField()),
                ('val3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
