# Generated by Django 5.2.5 on 2025-08-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_data',
        ),
    ]
