# Generated by Django 5.2.5 on 2025-08-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_api_document_delete_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='description',
        ),
    ]
