# Generated by Django 5.2.5 on 2025-08-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_api_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='balance',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
