# Generated by Django 5.2.5 on 2025-08-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_api_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='balance',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='user_data',
            name='balance',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
