# Generated by Django 5.2.5 on 2025-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_balance_api_amount_user_data_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='amount',
            field=models.FloatField(),
        ),
    ]
