# Generated by Django 5.2.5 on 2025-08-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_api_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='amount',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='balance',
            field=models.FloatField(),
        ),
    ]
