# Generated by Django 5.2.5 on 2025-08-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='lang',
            field=models.CharField(default='en', max_length=30),
            preserve_default=False,
        ),
    ]
