# Generated by Django 5.2.5 on 2025-08-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chats_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='Document2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.chats')),
            ],
        ),
    ]
