# Generated by Django 5.2.5 on 2025-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_chats_file_path_remove_chats_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='api_key',
            field=models.CharField(default='xyz', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chats',
            name='name',
            field=models.CharField(default='dd', max_length=30),
            preserve_default=False,
        ),
    ]
